Planning/Use_case/ECサイト.drawio

ユースケースを追加しました

---

Planning/ER_diagram/ER図.drawio

ER図を追加しました

---

Planning/遷移図/遷移図_ユーザー_カート一覧.drawio
Planning/遷移図/遷移図_ユーザー_ログイン.drawio
Planning/遷移図/遷移図_ユーザー_講座一覧.drawio
Planning/遷移図/遷移図_ユーザー_購入履歴.drawio
Planning/遷移図/遷移図_管理者_講座情報編集.drawio

0830_syouihou_sennizu

---

HTML_CSS/user_template.html

0831-fukuda-user_template追加

---

HTML_CSS/css/footer.css
HTML_CSS/css/header.css
HTML_CSS/kanrisha_template.html

0831-fukuda-footerを作成

---

HTML_CSS/css/header.css
HTML_CSS/user_template.html

user templateのHTMLとCSSを完成致しました

0831-Hoolan-user_templateを作成

---

HTML_CSS/user_register.html

0831-fukuda-新規登録画面作成

---

HTML_CSS/user_login_template.html

0831-syouihou-userLoginTemplate追加

---

HTML_CSS/css/user_register.css

0831-fukuda-register.css_fix

---

HTML_CSS/css/header.css

Header.cssを修正しました
headerを一番上の位置に固定しました

0901-Hoolan-Header.cssを修正しました

---

HTML_CSS/css/base.css
HTML_CSS/css/footer.css

0901-Hoolan-フッターのCSSを修正しました

---

HTML_CSS/admin_view_courses.html
HTML_CSS/css/admin_view_courses.css
HTML_CSS/css/footer.css
HTML_CSS/css/header.css
HTML_CSS/css/view_courses.css
HTML_CSS/user_view_courses.html

0901-Hoolan-admin_view_coursesを追加しました

---

HTML_CSS/admin_add_admin.html
HTML_CSS/css/admin_add_admin.css
HTML_CSS/css/base.css

0901-Hoolan-admin_add_admin.htmlを追加しました

---

HTML_CSS/admin_add_admin.html
HTML_CSS/user_edit_personal_info.html

user_edit_personal.html
admin_add_admin.html
<< の特別文字を使わないように&lt;&lt;に変更しました

0901-Hoolan-HTML変更

---

HTML_CSS/css/user_view_course_info.css
HTML_CSS/user_view_course_info.html

0901-fukuda-user_view_course_info追加

---

HTML_CSS/css/guest_header.css
HTML_CSS/css/user_view_course_info.css
HTML_CSS/guest_view_course_info.html
HTML_CSS/guest_view_courses.html

guest_view_courses.html
guest_view_course_info.html
を追加しました

0904-Hoolan-guest_view_courses and guest_view_course_info を追加

---

HTML_CSS/admin_add_course.html
HTML_CSS/css/admin_add_course.css

admin_add_courseのHTML CSS作成しました

0904-fukuda-admin_add_course作成

---

HTML_CSS/admin_edit_course.html
HTML_CSS/css/admin_edit_course.css
HTML_CSS/css/user_view_course_info.css

admin_edit_course作成
admin_add_course修正

0904-fukuda-admin_edit_course作成

---

TeamA/src/main/java/teamA/ex/controller/AdminLoginController.java
TeamA/src/main/java/teamA/ex/service/AdminService.java
TeamA/src/main/resources/templates/admin_login.html

AdmingLoginController 
AdminService
を追加しました

0904-Hoolan-管理者ログイン機能

---

TeamA/src/main/java/teamA/ex/model/entity/AdminEntity.java
TeamA/src/main/java/teamA/ex/model/entity/UserEntity.java

0904 syouihou entity

---

TeamA/logtest.txt
TeamA/pom.xml
TeamA/src/main/java/teamA/ex/controller/AdminLoginController.java
TeamA/src/main/java/teamA/ex/model/dao/AdminDao.java
TeamA/src/main/java/teamA/ex/model/entity/AdminEntity.java
TeamA/src/main/java/teamA/ex/service/AdminService.java
TeamA/src/main/resources/templates/admin_login.html

Spring Securityのせいでアップリを起動する時、アップリをアクセスするためにパスワードが必要でしたので、Spring　Securityを削除しました。

0905-Hoolan-Remove_spring_security

---

TeamA/logtest.txt
TeamA/pom.xml
TeamA/src/main/java/teamA/ex/controller/UserRegisterController.java
TeamA/src/main/java/teamA/ex/model/entity/CourseEntity.java
TeamA/src/main/java/teamA/ex/service/AdminService.java
TeamA/src/main/resources/templates/user_register.html

UserRegisterController 
CourseEntity
を追加しました

0905 hoolan user resgister controller

---

TeamA/logtest.txt
TeamA/src/main/java/teamA/ex/model/dao/CourseDao.java
TeamA/src/main/java/teamA/ex/model/dao/UserDao.java
TeamA/src/main/java/teamA/ex/model/entity/CourseEntity.java
TeamA/src/main/java/teamA/ex/model/entity/UserEntity.java
TeamA/src/main/java/teamA/ex/service/UserService.java

0905_syouihou_UserService

---

TeamA/src/main/java/teamA/ex/model/dao/CourseDao.java
TeamA/src/main/java/teamA/ex/model/entity/CourseEntity.java
TeamA/src/main/java/teamA/ex/service/CourseService.java

0905-Hoolan-CourseService createCourseを追加

---

TeamA/src/main/java/teamA/ex/controller/UserRegisterController.java
TeamA/src/main/java/teamA/ex/model/entity/UserEntity.java
TeamA/src/main/java/teamA/ex/service/UserService.java

UserServiceにuser_iconとhashPasswordを追加

0905-Hoolan clean UserServiceにuser_iconとhashPasswordを追加

---

TeamA/src/main/java/teamA/ex/model/dao/CourseDao.java

0905_syouihou_CourseDao

---

TeamA/src/main/resources/templates/admin_add_admin.html
TeamA/src/main/resources/templates/admin_add_course.html
TeamA/src/main/resources/templates/admin_edit_course.html
TeamA/src/main/resources/templates/admin_view_courses.html
TeamA/src/main/resources/templates/guest_view_course_info.html
TeamA/src/main/resources/templates/guest_view_courses.html
TeamA/src/main/resources/templates/user_confirm_payment_details.html
TeamA/src/main/resources/templates/user_edit_personal_info.html
TeamA/src/main/resources/templates/user_edit_user_confirm.html
TeamA/src/main/resources/templates/user_payment_confirmation.html
TeamA/src/main/resources/templates/user_select_payment_method.html
TeamA/src/main/resources/templates/user_view_cart.html
TeamA/src/main/resources/templates/user_view_course_info.html
TeamA/src/main/resources/templates/user_view_courses.html

HTMLのCSSをth:hrefに変更
ユーザーアイコンをth:srcに変更

0906-fukuda-HTMLのCSSをthに変更

---

TeamA/src/main/java/teamA/ex/model/dao/CourseDao.java

0906_syouihou_courseDao

---

TeamA/src/main/java/teamA/ex/controller/UserCurtController.java

UserCurtControllerのマッピングとcourseServiceのメソッド名を修正して、一時的に安定しました。

0908-Hoolan-Mainを安定しました

---

TeamA/pom.xml
TeamA/src/main/java/teamA/ex/service/TransactionHistoryService.java

TransactionHistoryServiceを完成しました

0911-okashin-TransactionHistoryService

---

TeamA/src/main/java/teamA/ex/controller/AdminContactController.java
TeamA/src/main/java/teamA/ex/controller/ContactController.java

adminContactController が完成しました

0914_syouihou_adminContactController

---

TeamA/src/main/resources/static/css/footer.css

0915_syouihou_css_fix

---

TeamA/src/main/java/teamA/ex/controller/AdminContactController.java
TeamA/src/main/java/teamA/ex/model/dao/ContactRepository.java
TeamA/src/main/java/teamA/ex/model/entity/Contact.java
TeamA/src/main/java/teamA/ex/model/entity/ContactEntityPK.java
TeamA/src/main/java/teamA/ex/service/NewContactService.java
TeamA/src/main/resources/templates/admin_contact.html

0920_syouihou_ContactRepository
